// make me a github action that runs the tests on every push to master
name: Run tests on push to master
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run build